name: Scheduled Job Actions Check 

on:
  push:
    branches:
      - master 
  schedule:
    - cron: '0 21 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Print the current time 
        run: echo "[`date +'%d/%m/%Y %T'`] Time to check the lending status!"
      - name: Trigger the check through API call 
        run: curl -X GET ${{ secrets.SERVER_URL }}
